#!/bin/sh

set -e -x
make mrproper
rm -rf out
mkdir -p out

export ARCH=arm
export CROSS_COMPILE=arm-linux-gnueabi-
export KCFLAGS=-w
export CONFIG_SECTION_MISMATCH_WARN_ONLY=y
export CFLAGS_WARN=-Wunused-but-set-variable
export xxx="KCFLAGS=-w CONFIG_SECTION_MISMATCH_WARN_ONLY=y CFLAGS_WARN=-Wunused-but-set-variable ARCH=arm CROSS_COMPILE=arm-linux-gnueabi-"

sed -i '/^inline bool need_memory_boosting/,/^}$/d' mm/vmscan.c
sed -i 's/^inline void blk_crypto_flock/void blk_crypto_flock/' include/linux/blk-crypto.h

make O=out $xxx a022m_defconfig
make O=out $xxx -j"$(nproc --all)" zImage-dtb 2>&1 | tee build.log
