#!/bin/sh

set -e -x

# Kernel Source
KERNEL_SOURCE="https://github.com/rdbckp/Q"
KERNEL_BRANCH="main"

# Setup Folder
WORK="${GITHUB_WORKSPACE}/work"
KERNEL="myKernel"
KERNEL_SRC="${WORK}/${KERNEL}"
mkdir -p "${WORK}"

# Cloning kernel
cd $WORK
[ ! -d "${KERNEL}" ] && git clone --depth=1 "${KERNEL_SOURCE}" -b "${KERNEL_BRANCH}" "${KERNEL}"
