#!/bin/sh

make mrproper
set -e -x
export PATH="$(pwd)/toolchain/clang/bin:${PWD}/toolchain/gcc/bin:${PATH}"
rm -rf out
mkdir -p out

export ARCH=arm
export CC=clang
export HOSTCC=clang
export CROSS_COMPILE=arm-linux-androideabi-
export KCFLAGS=-w
export CONFIG_SECTION_MISMATCH_WARN_ONLY=y
export CFLAGS_WARN=-Wunused-but-set-variable
export xxx="KCFLAGS=-w CONFIG_SECTION_MISMATCH_WARN_ONLY=y CFLAGS_WARN=-Wunused-but-set-variable ARCH=arm CC=clang HOSTCC=clang CROSS_COMPILE=arm-linux-androideabi-"
sed -i 's/CONFIG_LOCALVERSION="-RooXie_SM-A022F"/CONFIG_LOCALVERSION="-Rawon_SM-A022F"/' arch/arm/configs/a02_defconfig
sed -i 's/CONFIG_KERNEL_GZIP=y/# CONFIG_KERNEL_GZIP is not set/' arch/arm/configs/a02_defconfig
sed -i 's/# CONFIG_KERNEL_LZ4 is not set/CONFIG_KERNEL_LZ4=y/' arch/arm/configs/a02_defconfig
sed -i '4s/SUBLEVEL = 336/SUBLEVEL = 186/' Makefile
make O=out $xxx a02_defconfig
make O=out $xxx -j"$(nproc --all)" 2>&1 | tee build.log
