#!/bin/sh

set -e -x
make mrproper
rm -rf out
mkdir -p out

export ARCH=arm
export CROSS_COMPILE=arm-linux-gnueabi-
export KCFLAGS=-w
export CONFIG_SECTION_MISMATCH_WARN_ONLY=y
export CFLAGS_WARN=-Wunused-but-set-variable
export xxx="KCFLAGS=-w CONFIG_SECTION_MISMATCH_WARN_ONLY=y CFLAGS_WARN=-Wunused-but-set-variable ARCH=arm CROSS_COMPILE=arm-linux-gnueabi-"

cp mm/vmscan.c mm/vmscan.c.bak && sed -i '/^inline bool need_memory_boosting/,/^}$/d' mm/vmscan.c
cp include/linux/mm.h include/linux/mm.h.bak && sed -i '2886s/.*/static inline bool need_memory_boosting(struct pglist_data *pgdat) { return false; }/' include/linux/mm.h
cp include/linux/blk-crypto.h include/linux/blk-crypto.h.bak && sed -i 's/^inline void blk_crypto_flock/void blk_crypto_flock/' include/linux/blk-crypto.h
cp include/linux/keyslot-manager.h include/linux/keyslot-manager.h.bak && sed -i 's/^inline void ksm_flock/void ksm_flock/' include/linux/keyslot-manager.h
cp drivers/misc/mediatek/eccci/hif/net_speed_monitor.c drivers/misc/mediatek/eccci/hif/net_speed_monitor.c.bak && sed -i 's/\t\tspeed = speed \/ 1000LL;/\t\tdo_div(speed, 1000LL);/' drivers/misc/mediatek/eccci/hif/net_speed_monitor.c
cp arch/arm/boot/compressed/head.S arch/arm/boot/compressed/head.S.bak && sed -i 's/\.section "\.start", #alloc, #execinstr/.section ".start"/' arch/arm/boot/compressed/head.S
cp arch/arm/boot/compressed/piggy.S arch/arm/boot/compressed/piggy.S.bak && sed -i 's/,#alloc//' arch/arm/boot/compressed/piggy.S
cp arch/arm/mm/proc-v7.S arch/arm/mm/proc-v7.S.bak && sed -i 's/\.section "\.proc\.info\.init", #alloc/.section ".proc.info.init"/' arch/arm/mm/proc-v7.S

make O=out $xxx a022m_defconfig
make O=out $xxx -j"$(nproc --all)" zImage-dtb 2>&1 | tee build.log