#!/bin/bash
# export PATH="/opt/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH"
make mrproper
set -e -x
export PATH="$(pwd)/toolchain/clang2/bin:${PWD}/toolchain/gcc/bin:${PATH}"
rm -rf out
mkdir -p out

export ARCH=arm64
export CC=clang
export HOSTCC=clang
export CROSS_COMPILE=aarch64-linux-android-
export KCFLAGS=-w
export CONFIG_SECTION_MISMATCH_WARN_ONLY=y
export CFLAGS_WARN=-Wunused-but-set-variable
export xxx="KCFLAGS=-w CONFIG_SECTION_MISMATCH_WARN_ONLY=y CFLAGS_WARN=-Wunused-but-set-variable ARCH=arm64 CC=clang HOSTCC=clang CROSS_COMPILE=aarch64-linux-android-"
make O=out $xxx a02_64_defconfig
make O=out $xxx -j"$(nproc --all)" 2>&1 | tee build.log
