name: Warning! Delete all

on:
  workflow_dispatch:

jobs:
  Cleaning:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Working
      run: |
        cd ${GITHUB_WORKSPACE}
        cp -rf .github/workflows sriptsgw/.
        cd .github && cd workflows
        rm -rf *
        cd ${GITHUB_WORKSPACE}
        cp scriptsgw/workflows/build_*.yml .github/workflows/.
        cp scriptsgw/workflows/sapu.yml .github/workflows/.
        cp scriptsgw/workflows/del.yml .github/workflows/.
        rm -rf scriptsgw/workflow
        
    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "actions@github.com"
        
    - name: Add and Commit file
      run: |
        git add -A
        git commit -m "Initial"
        git push
