name: Build Up
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Kernel
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Toolchain & Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bc build-essential flex bison libssl-dev libelf-dev gcc-arm-linux-gnueabi

      - name: Apply Upstream Patch (v187 to v190)
        run: |
          git remote add stable https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git
          git fetch stable tag v4.14.187 tag v4.14.190 --no-tags --depth 1
          git diff v4.14.187 v4.14.190 -- arch/arm/ drivers/ include/ kernel/ mm/ net/ sound/ Makefile > p190_clean.patch
          patch -p1 --forward --batch < p190_clean.patch

      - name: Build Kernel
        run: |
          chmod +x z
          ./z

      - name: Upload zImage
        uses: actions/upload-artifact@v4
        with:
          name: _RooXie-v190-
          path: out/arch/arm/boot/zImage
