name: Build Up
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Kernel
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Toolchain & Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bc build-essential flex bison libssl-dev libelf-dev gcc-arm-linux-gnueabi

      - name: Apply Upstream Patch (v187 to v190)
        run: |
          CURRENT_SUBLEVEL=$(grep "^SUBLEVEL =" Makefile | awk '{print $3}')
          
          if [ "$CURRENT_SUBLEVEL" -eq "190" ]; then
            echo "code accepted!"
          else
            git remote add stable https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git || true
            git fetch stable tag v4.14.187 tag v4.14.190 --no-tags --depth 1
            git diff v4.14.187 v4.14.190 -- arch/arm/ drivers/ include/ kernel/ mm/ net/ sound/ Makefile > p190_clean.patch
            patch -p1 --forward --batch < p190_clean.patch || echo "Patch successful"
          fi

      - name: Fix MediaTek SPI Header (The Dirty Way)
        run: |
          sed -i '40i #ifndef SPI_ADJUST_CFG0_SCK_LOW_OFFSET\n#define SPI_ADJUST_CFG0_SCK_LOW_OFFSET 0\n#endif' drivers/spi/spi-mt65xx.c
          head -n 45 drivers/spi/spi-mt65xx.c

      - name: Build Kernel
        run: |
          chmod +x z
          ./z

      - name: Upload zImage
        uses: actions/upload-artifact@v4
        with:
          name: _RooXie-v190-
          path: out/arch/arm/boot/zImage
