name: Unpack Repack Recovery

on:
  workflow_dispatch:

jobs:
  repack-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup AIK-Linux
        run: |
          sudo apt-get update
          sudo apt-get install -y p7zip-full cpio python3
          
          git clone https://github.com/osm0sis/Android-Image-Kitchen.git AIK
          
          # Fix: Masuk ke folder AIK dulu baru chmod
          cd AIK
          chmod -R 755 *.sh
          find tools -type f -executable -exec chmod 755 {} +
          cd ..

      - name: Repack Process
        run: |
          # 1. Cek isi direktori awal buat mastiin file ada
          ls -l
          
          # 2. Copy amunisi ke folder AIK
          # Kita pake path absolut biar aman
          cp ${GITHUB_WORKSPACE}/recovery.img ${GITHUB_WORKSPACE}/AIK/
          cp ${GITHUB_WORKSPACE}/zImage ${GITHUB_WORKSPACE}/AIK/zImage_new
          
          # 3. Eksekusi di dalem folder AIK
          cd ${GITHUB_WORKSPACE}/AIK
          
          # Unpack
          ./unpackimg.sh recovery.img
          
          # Ganti kernel (tiban file lama di split_img)
          cp zImage_new split_img/recovery.img-kernel
          
          # Repack
          ./repackimg.sh
          
          # 4. Pindahin hasil keluar dan kasih nama
          DATE_TIME=$(TZ='Asia/Jakarta' date +"%d%b_%I_%M%p")
          mv image-new.img ../TWRP-A02-${DATE_TIME}.img

      - name: Upload Repacked Recovery
        uses: actions/upload-artifact@v4
        with:
          name: Recovery-TWRP-A02
          path: TWRP-A02-*.img
