name: Delete Some YML not needed anymore

on:
  workflow_dispatch:

jobs:
  Cleaning:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Working
      run: |
        cd ${GITHUB_WORKSPACE}
        mkdir -p .github/bckp
        mv .github/workflows/build_*.yml .github/bckp/.
        mv .github/workflows/del.yml .github/bckp/.
        mv .github/workflows/sapu.yml .github/bckp/.
        cd .github && cd workflows
        rm -rf *
        cd ${GITHUB_WORKSPACE}
        mv .github/bckp/*.yml .github/workflows/.
        rm -rf .github/bckp
        
    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "actions@github.com"
        
    - name: Add and Commit file
      run: |
        git add -A
        git commit -m "Initial"
        git push
